apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-se4m
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-se4m@sha256:bb6bf5770dfebf60374c78ddc4f62298bae39e1dc1ee1015d2814975a1815ece
        name: my-nodejs
        resources: {}
status: {}
